# Generated by Django 2.1.5 on 2019-01-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190123_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
